# Generated by Django 4.1.7 on 2023-05-16 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_stepbase_stepsort_steprecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepsort',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stepsort',
            name='order_type',
        ),
        migrations.CreateModel(
            name='StepSortChangeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('order_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.ordertype', verbose_name='订单类型')),
                ('step_sort_first', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.stepsort', verbose_name='步骤排序')),
            ],
            options={
                'verbose_name': '步骤排序变更记录',
                'verbose_name_plural': '步骤排序变更记录',
                'db_table': 's_order_step_sort_change_record',
            },
        ),
    ]
