# Generated by Django 4.1.7 on 2023-05-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_stepsort_notes_remove_stepsort_order_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stepsortchangerecord',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
