# Generated by Django 4.1.7 on 2023-05-29 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(max_length=100, verbose_name='员工编号')),
                ('phone_number', models.CharField(max_length=100, verbose_name='手机号')),
                ('avatar', models.ImageField(upload_to='staff', verbose_name='头像')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '员工',
                'verbose_name_plural': '员工列表',
                'db_table': 's_staff_base',
            },
        ),
    ]
