# Generated by Django 4.1.7 on 2024-01-31 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staffbase_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffbase',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='手机号'),
        ),
    ]
