# Generated by Django 4.1.7 on 2024-02-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staffbase_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffbase',
            name='full_name',
            field=models.CharField(max_length=100, null=True, verbose_name='员工姓名'),
        ),
    ]
