# Generated by Django 4.1.7 on 2023-04-29 09:11

import customer.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='客户名称')),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='公司名称')),
                ('contact_number', models.CharField(max_length=20, unique=True, verbose_name='联系电话')),
                ('avatar', models.ImageField(upload_to=customer.utils.get_upload_path, verbose_name='头像')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户列表',
                'db_table': 's_customer_base',
            },
        ),
    ]
