# Generated by Django 4.1.7 on 2024-01-31 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hf_system.core.models.structure_module_base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, unique=True, verbose_name='角色名称')),
                ('role_desc', models.CharField(max_length=100, verbose_name='角色描述')),
                ('role_label', models.CharField(max_length=100, verbose_name='角色标识')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色列表',
                'db_table': 's_manager_role',
            },
            bases=(hf_system.core.models.structure_module_base.StructureModuleBase, models.Model),
        ),
        migrations.CreateModel(
            name='SPremission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限名称')),
                ('permission_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限描述')),
                ('permission_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('menu_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('menu_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.spremission', verbose_name='父级权限')),
                ('roles', models.ManyToManyField(to='manager.srole', verbose_name='角色')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限列表',
                'db_table': 's_manager_permission',
            },
            bases=(hf_system.core.models.structure_module_base.StructureModuleBase, models.Model),
        ),
    ]
