# Generated by Django 4.1.7 on 2023-04-29 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('factory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='订单类型')),
            ],
            options={
                'verbose_name': '订单类型',
                'verbose_name_plural': '订单类型管理',
                'db_table': 's_order_type',
            },
        ),
        migrations.CreateModel(
            name='OrderBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=100, verbose_name='订单号')),
                ('order_product', models.CharField(max_length=100, null=True, verbose_name='产品名称')),
                ('model_base', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='factory.modelinfo', verbose_name='模具名称')),
                ('order_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.ordertype', verbose_name='订单类型')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单列表',
                'db_table': 's_order_base',
            },
        ),
    ]
