# Generated by Django 4.1.7 on 2023-05-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_orderbase_options_orderlist_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='notes',
            field=models.TextField(blank=True, verbose_name='备注'),
        ),
    ]
