# Generated by Django 4.1.7 on 2023-05-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderlist_create_time_orderlist_update_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='StepBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='步骤名称')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '步骤',
                'verbose_name_plural': '步骤列表',
                'db_table': 's_order_step_base',
            },
        ),
        migrations.CreateModel(
            name='StepSort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_skip', models.BooleanField(default=True, verbose_name='是否跳过')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('child_step', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='order.stepsort', verbose_name='子步骤')),
                ('order_type', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.ordertype', verbose_name='订单类型')),
                ('parent_step', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_steps', to='order.stepsort', verbose_name='父步骤')),
                ('step_base', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.stepbase', verbose_name='步骤')),
            ],
            options={
                'verbose_name': '步骤排序',
                'verbose_name_plural': '步骤排序',
                'db_table': 's_order_step_sort',
            },
        ),
        migrations.CreateModel(
            name='StepRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('order_list', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.orderlist', verbose_name='所属订单')),
                ('step_sort', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='order.stepsort', verbose_name='步骤排序')),
            ],
            options={
                'verbose_name': '步骤记录',
                'verbose_name_plural': '步骤记录',
                'db_table': 's_order_step_record',
            },
        ),
    ]
