# Generated by Django 4.1.7 on 2023-05-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_stepsortchangerecord_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepsort',
            name='child_step',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='子步骤'),
        ),
        migrations.AlterField(
            model_name='stepsort',
            name='parent_step',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='父步骤'),
        ),
    ]
