# Generated by Django 4.1.7 on 2023-05-23 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_child_step_stepsort_child_step_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepsortchangerecord',
            name='step_sort_first',
        ),
        migrations.AddField(
            model_name='stepsort',
            name='record_id',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.CASCADE, to='order.stepsortchangerecord', verbose_name='变更记录'),
            preserve_default=False,
        ),
    ]
