# Generated by Django 4.1.7 on 2023-05-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_rename_record_id_stepsort_record'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepsort',
            old_name='record',
            new_name='change_record',
        ),
    ]
