# Generated by Django 4.1.7 on 2023-05-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_stepbase_is_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='order_price',
            field=models.FloatField(default=0.0, verbose_name='单价'),
        ),
    ]
