# Generated by Django 4.1.7 on 2023-06-05 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100, verbose_name='角色名称')),
                ('role_desc', models.CharField(max_length=100, verbose_name='角色描述')),
                ('role_label', models.CharField(max_length=100, verbose_name='角色标识')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_user', models.BigIntegerField(verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_user', models.BigIntegerField(blank=True, null=True, verbose_name='删除人')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色列表',
                'db_table': 's_admin_role',
            },
        ),
        migrations.CreateModel(
            name='SPremission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限名称')),
                ('permission_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限描述')),
                ('permission_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='权限标识')),
                ('menu_icon', models.CharField(blank=True, max_length=100, null=True, verbose_name='图标')),
                ('menu_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='链接')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_user', models.BigIntegerField(verbose_name='创建人')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_user', models.BigIntegerField(verbose_name='更新人')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_user', models.BigIntegerField(blank=True, null=True, verbose_name='删除人')),
                ('delete_time', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminExt.spremission', verbose_name='父级权限')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限列表',
                'db_table': 's_admin_permission',
            },
        ),
    ]
