# Generated by Django 4.1.7 on 2024-02-27 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminExt', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srole',
            name='users',
        ),
        migrations.DeleteModel(
            name='SPremission',
        ),
        migrations.DeleteModel(
            name='SRole',
        ),
    ]
