# Generated by Django 4.1.7 on 2023-06-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminExt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spremission',
            name='roles',
            field=models.ManyToManyField(to='adminExt.srole', verbose_name='角色'),
        ),
    ]
