# Generated by Django 4.1.7 on 2023-06-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminExt', '0003_alter_srole_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srole',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
