# Generated by Django 4.1.7 on 2023-06-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminExt', '0004_alter_srole_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spremission',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
