# Generated by Django 4.1.7 on 2023-06-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminExt', '0005_alter_spremission_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='spremission',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
