# Generated by Django 4.1.7 on 2023-06-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminExt', '0006_spremission_is_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='srole',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='是否删除'),
        ),
    ]
